image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build-local:
  stage: build
  image: adoptopenjdk/openjdk11:alpine-slim
  script:
  - ./gradlew assemble
  - echo "you built the app"

  artifacts:
    paths:
      -  build/libs/*.jar

build-tf:
  extends: .terraform:build

test-job1:
  stage: test
  image: openjdk:11
  script:
    - echo "This job tests something"
    - ./gradlew test
  allow_failure: true



