stages:
  - build
  - test

build:
  stage: build
  image: openjdk:11
  script:
  - ./gradlew build
  - echo "you built the app"

  artifacts:
    paths:
      - build/libs/g-hello-0.0.1-SNAPSHOT.jar

test-job1:
  stage: test
  image: openjdk:11
  script:
    - echo "This job tests something"
    - ./gradlew test
  allow_failure: true


