# image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
 TF_STATE_NAME: default
 TF_CACHE_KEY: default

include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - build1
  - build2
  - test
  - deploy

build-local:
  stage: build1
  image: adoptopenjdk/openjdk11:alpine-slim
  script:
  - ./gradlew assemble
  - echo "you built the app"

  artifacts:
    paths:
      -  build/libs/*.jar

build-tf:
  extends: .terraform:build
  stage: build2
  dependencies:
    - "build-local"

test-job1:
  stage: test
  image: openjdk:11
  script:
    - echo "This job tests something"
    - ./gradlew test
  allow_failure: true



